### ISSUE TITLE
不支持MAC电脑吗

### ISSUE THREAD

**Issue by guochenchn** [lovelyjuice/jdread-downloader#5]
无法打开MAC中的chrome

**Comment by lovelyjuice** [comment]
没有mac，不太清楚

**Comment by guochenchn** [comment]
我用了windows 执行完那行代码，浏览器打开了 地址栏是data，没有跳转到指定页面，手动打开到指定页面，输入指令没有爬取，有遇到这样的问题吗

**Comment by guochenchn** [comment]
Exception in thread "main" org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:54747/devtools/browser/44ca6f6d-0782-4c2c-a8f5-e4f92985e070
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'localhost', ip: 'fe80:0:0:0:c56:5cc6:9515:8dc0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '11.0.18'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:106)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:116)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:81)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:49)
	at io.github.lovelyjuice.Main.main(Main.java:21)
	
	报了这个错误
